# Generated by Django 5.2.12 on 2026-03-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_plateforme', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_prestatire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('WALLET', 'Wallet')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succes'), ('ECHOUE', 'Echoue'), ('REMBOURSE', 'Rembourse')], default='EN_ATTENTE', max_length=20)),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='accounts.clientprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traite'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20)),
                ('methode_retrait', models.CharField(default='MOBILE_MONEY', max_length=50)),
                ('numero_mobile', models.CharField(max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('prestatire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='accounts.prestatireprofile')),
            ],
            options={
                'verbose_name': 'Retrait',
                'verbose_name_plural': 'Retraits',
                'ordering': ['-date_demande'],
            },
        ),
    ]
