# Generated by Django 5.2.12 on 2026-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_virement',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle l admin a validé et viré les fonds au prestataire', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='fonds_bloques',
            field=models.BooleanField(default=True, help_text='True = fonds en attente de validation admin. False = virés au prestataire.'),
        ),
    ]
