# Generated by Django 5.2.12 on 2026-03-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pricing_type', models.CharField(choices=[('FIXE', 'Prix fixe'), ('PAR_UNITE', 'Par unite'), ('SUR_DEVIS', 'Sur devis')], default='FIXE', max_length=20)),
                ('prix_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.category')),
                ('prestatire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.prestatireprofile')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='services.service')),
            ],
            options={
                'verbose_name': 'Disponibilite',
                'verbose_name_plural': 'Disponibilites',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('is_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'Image Service',
                'verbose_name_plural': 'Images Service',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ServiceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('NUMBER', 'Nombre'), ('SELECT', 'Selection'), ('BOOLEAN', 'Oui/Non')], max_length=20)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='services.service')),
            ],
            options={
                'verbose_name': 'Parametre Service',
                'verbose_name_plural': 'Parametres Service',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ServiceParameterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('prix_supplementaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.serviceparameter')),
            ],
            options={
                'verbose_name': 'Option Parametre',
                'verbose_name_plural': 'Options Parametre',
            },
        ),
    ]
