# Generated by Django 5.2.12 on 2026-03-11 12:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='fichier',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='kyc'),
        ),
        migrations.AlterField(
            model_name='prestatireprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
