# Generated by Django 5.2.12 on 2026-03-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientprofile_avatar_alter_kycdocument_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='type_document',
            field=models.CharField(choices=[('CNI', 'Carte Nationale Identite'), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('AUTRE', 'Autre')], max_length=20),
        ),
    ]
