# Generated by Django 5.2.12 on 2026-03-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('COMPORTEMENT', 'Comportement inapproprie'), ('ARNAQUE', 'Arnaque'), ('CONTENU_INAPPROPRIE', 'Contenu inapproprie'), ('AUTRE', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traite'), ('REJETE', 'Rejete')], default='EN_ATTENTE', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date'],
            },
        ),
    ]
