# Generated by Django 5.2.12 on 2026-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
