# Generated by Django 5.2.12 on 2026-03-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_kycdocument_type_document'),
        ('feed', '0001_initial'),
        ('services', '0002_alter_serviceimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_services', to='accounts.clientprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='services.service')),
            ],
            options={
                'verbose_name': 'Favori Service',
                'verbose_name_plural': 'Favoris Services',
                'unique_together': {('client', 'service')},
            },
        ),
    ]
