# Generated by Django 5.2.12 on 2026-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_favoriservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.URLField(),
        ),
    ]
