# Generated by Django 5.2.12 on 2026-03-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_NEGOCIATION', 'En negociation'), ('ACCEPTE', 'Accepte'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ANNULE', 'Annule')], default='EN_NEGOCIATION', max_length=20)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parametres_choisis', models.JSONField(blank=True, default=dict)),
                ('notes_client', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_debut_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.clientprofile')),
                ('prestatire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='accounts.prestatireprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='services.service')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='orders.order')),
            ],
            options={
                'verbose_name': 'Negociation',
                'verbose_name_plural': 'Negociations',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historique Statut',
                'verbose_name_plural': 'Historiques Statuts',
                'ordering': ['-date'],
            },
        ),
    ]
