# Generated by Django 5.2.12 on 2026-03-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOUVEAU_MESSAGE', 'Nouveau message'), ('COMMANDE_RECUE', 'Commande recue'), ('COMMANDE_ACCEPTEE', 'Commande acceptee'), ('COMMANDE_TERMINEE', 'Commande terminee'), ('COMMANDE_ANNULEE', 'Commande annulee'), ('NOUVEAU_STATUT', 'Nouveau statut'), ('PAIEMENT_RECU', 'Paiement recu'), ('RETRAIT_TRAITE', 'Retrait traite'), ('NOUVEL_AVIS', 'Nouvel avis'), ('NOUVEAU_PRESTATAIRE_PROCHE', 'Nouveau prestataire proche'), ('KYC_VALIDE', 'KYC valide'), ('KYC_REJETE', 'KYC rejete')], max_length=40)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('lien_objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lien_objet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date'],
            },
        ),
    ]
